# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 685ef68addf3d10d23a5bf06b4a4b9694787bbc5d6cc0df7c79f30fcfcdee24672a4e7c8fc988c296dece8b64076485e80f9f467d61c20344c9505377a76a17c

test:
  secret_key_base: 1689d3bb17000f1e91d0c498ab6916daaf176f74385de7db390f6c1df0821309c580941dbc877819c9f2c5ee1df6ff04668abe414715842370f8fdfe702d2faf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
